sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8.9.1"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod --aot
  - ng test
